language: go
arch:
    - amd64
    - ppc64le
go_import_path: github.com/inconshreveable/log15
sudo: false
arch:
  - AMD64
  - ppc64le
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master
