name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-20.04, macos-10.15, windows-2019 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive --force
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install build-essential
          fi
        shell: bash
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Lint
        if: matrix.os == 'ubuntu-20.04'
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
      - run: go test ./...

