on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
      with:
         path: './src/github.com/inconshreveable/log15'
    - name: Run tests for v3
      run: |
        go vet -trimpath ./...
        go test -trimpath -race ./...
      working-directory: './src/github.com/inconshreveable/log15/v3'
    - name: Run tests for compat
      run: |
        go vet -trimpath ./...
        go test -trimpath -race ./...
      working-directory: './src/github.com/inconshreveable/log15/compat'
    - name: Run tests for v2
      run: |
        go vet -trimpath ./...
        go test -trimpath ./...
      working-directory: './src/github.com/inconshreveable/log15'
